# Generated by Django 5.2.5 on 2025-08-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(max_length=100000),
        ),
    ]
