# Generated by Django 5.2.5 on 2025-08-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0002_alter_tweet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
